/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-uehFbaYqiBvyKM-twNfXLF68IsgXncjxg4ULnKVAvb-pPwPhFyThcJe-8ZLZ8Jzj20eACYUQ0PoZhLopFsAoldc5DvvPNBN1BLzBv1xx5ak5oNDdgT64Ioaz",
  "tt": "tt-1-t6xXEoJCG3l--2ugQgMvBGCX3fxlvnO7yV4pCyKEoGk=",
  "version": "2020-11-20"
}

export default ebconfig;